using UnityEngine;

namespace MapGen
{

    // These SOs are generated by MapGenerator and should not be created manually.
    public class MapRoomData : ScriptableObject
    {
        [SerializeField] public string roomGuid;
        [SerializeField] public string roomName;
        [SerializeField] MapRoomLayer _backgroundLayer;
        [SerializeField] MapRoomLayer _borderLayer;
        [SerializeField] MapRoomLayer _tileLayer;
        [Space]
        [Space]
        [SerializeField] bool isVisited;

        public string RoomGuid => roomGuid;
        public bool IsVisited => isVisited;

        public MapRoomLayer backgroundLayer => _backgroundLayer;
        public MapRoomLayer borderLayer => _borderLayer;
        public MapRoomLayer tileLayer => _tileLayer;

        public event System.Action<string> OnRoomVisited;

        public void Init()
        {
            isVisited = false;
        }

        public void FlagRoomVisited()
        {
            isVisited = true;
            OnRoomVisited?.Invoke(roomGuid);
        }

        public void SetBackgroundLayer(MapRoomLayer incoming)
        {
            _backgroundLayer.Config(incoming);
        }

        public void SetBorderLayer(MapRoomLayer incoming)
        {
            _borderLayer.Config(incoming);
        }

        public void SetTileLayer(MapRoomLayer incoming)
        {
            _tileLayer.Config(incoming);
        }

        public void SetBackgroundSprite(Sprite sprite)
        {
            _backgroundLayer.sprite = sprite;
        }

        public void SetBorderSprite(Sprite sprite)
        {
            _borderLayer.sprite = sprite;
        }

        public void SetTileSprite(Sprite sprite)
        {
            _tileLayer.sprite = sprite;
        }

        public GameObject CreateGameObject()
        {
            GameObject backgroundObj = _backgroundLayer.CreateGameObject();
            GameObject borderObj = _borderLayer.CreateGameObject();
            GameObject tileObj = _tileLayer.CreateGameObject();
            GameObject roomObj = new GameObject($"MapRoom_{roomName}");
            roomObj.transform.position = Vector2.zero;
            if (backgroundObj != null) backgroundObj.transform.SetParent(roomObj.transform);
            if (borderObj != null) borderObj.transform.SetParent(roomObj.transform);
            if (tileObj != null) tileObj.transform.SetParent(roomObj.transform);
            return roomObj;
        }

        public override string ToString()
        {
            return $"{roomName}-{roomGuid}\n{_borderLayer}\n{_tileLayer}\n{_backgroundLayer}";
        }
    }
}

// Okay, so we have a big fuckin' map with lots of sprites. Map component needs to know
// if / when to turn each of these sprites on.

// Creating the map and saving the prefab shouldn't be difficult. Editing the prefab shouldn't
// be difficult. We just:
// - Use a dictionary - `Dictionary<Guid, GameObject>`
// - Update `mapRoomDataList` array with the current list of MapRoomData SOs
// - Iterate through this list, checking Dictionary<Guid, GameObject>
// - If GameObject exists, replace the sprites with GetSprite()
// - If GameObject does not exist, append a new MapRoom GO as a child of Map
// - Hierarchy:
//      Map
//          MapRoom
//              - MapRoomSprite
//              - MapRoomSprite
//              - MapRoomSprite
//          MapRoom
//              - MapRoomSprite
//              - MapRoomSprite
//              - MapRoomSprite
// - Just enable/disable each MapRoom


// Okay, so that's the Map prefab itself.


