using UnityEngine;

namespace MapGen
{

    // These SOs are generated by MapGenerator and should not be created manually.
    public class MapRoomData : ScriptableObject
    {
        public string roomGuid;
        public string roomName = string.Empty;
        public MapRoomLayer backgroundLayer;
        public MapRoomLayer borderLayer;
        public MapRoomLayer tileLayer;
        [Space]
        [Space]
        [SerializeField] bool isVisited;

        public string RoomGuid => roomGuid;
        public bool IsVisited => isVisited;

        public event System.Action<string> OnRoomVisited;

        public void Init()
        {
            isVisited = false;
        }

        public void FlagRoomVisited()
        {
            isVisited = true;
            OnRoomVisited?.Invoke(roomGuid);
        }

        public GameObject CreateGameObject()
        {
            GameObject backgroundObj = backgroundLayer.CreateGameObject();
            GameObject borderObj = borderLayer.CreateGameObject();
            GameObject tileObj = tileLayer.CreateGameObject();
            GameObject roomObj = new GameObject($"MapRoom_{roomName}");
            roomObj.transform.position = Vector2.zero;
            if (backgroundObj != null) backgroundObj.transform.SetParent(roomObj.transform);
            if (borderObj != null) borderObj.transform.SetParent(roomObj.transform);
            if (tileObj != null) tileObj.transform.SetParent(roomObj.transform);
            return roomObj;
        }

        public override string ToString()
        {
            return $"{roomGuid}\n{borderLayer}\n{tileLayer}\n{backgroundLayer}";
        }
    }
}

// Okay, so we have a big fuckin' map with lots of sprites. Map component needs to know
// if / when to turn each of these sprites on.

// Creating the map and saving the prefab shouldn't be difficult. Editing the prefab shouldn't
// be difficult. We just:
// - Use a dictionary - `Dictionary<Guid, GameObject>`
// - Update `mapRoomDataList` array with the current list of MapRoomData SOs
// - Iterate through this list, checking Dictionary<Guid, GameObject>
// - If GameObject exists, replace the sprites with GetSprite()
// - If GameObject does not exist, append a new MapRoom GO as a child of Map
// - Hierarchy:
//      Map
//          MapRoom
//              - MapRoomSprite
//              - MapRoomSprite
//              - MapRoomSprite
//          MapRoom
//              - MapRoomSprite
//              - MapRoomSprite
//              - MapRoomSprite
// - Just enable/disable each MapRoom


// Okay, so that's the Map prefab itself.


